[package]
name = "rhttp"
version = "0.1.0"
edition = "2021"

members = [
  "proc_macros"
]

[dependencies]
serde = {version="1.0.210", features=["derive"]}
serde_json = "1.0.128"
url = "2.5.2"
proc_macros = {path = "./proc_macros"}
serde_qs = "0.13.0"
bytes = "1.8.0"
