[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.8.0"
serde = {version="1.0.210", features=["derive"]}
serde_json = "1.0.128"
serde_qs = "0.13.0"
mime = "0.3.17"
chrono = "0.4.38"
thiserror = "2.0.7"
